DROP TABLE IF EXISTS `PHOTOS` ;
DROP TABLE IF EXISTS `MOSAICS` ;

CREATE TABLE IF NOT EXISTS `MOSAICS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NOT NULL DEFAULT 'default',
  `title` VARCHAR(45) NOT NULL DEFAULT 'default',
  `contents` VARCHAR(140) NOT NULL DEFAULT 'default',
  PRIMARY KEY (`id`));

CREATE TABLE IF NOT EXISTS `PHOTOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `unique_id` VARCHAR(60) NOT NULL,
  `original_name` VARCHAR(45) NOT NULL,
  `width` INT NOT NULL,
  `height` INT NOT NULL,
  `position_x` INT NOT NULL DEFAULT 0,
  `position_y` INT NOT NULL DEFAULT 0 COMMENT '	 ',
  `MOSAICS_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PHOTOS_MOSAICS_idx` (`MOSAICS_id` ASC),
  CONSTRAINT `fk_PHOTOS_MOSAICS`
    FOREIGN KEY (`MOSAICS_id`)
    REFERENCES `MOSAICS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
